MFH: r514602 r515847
converters/pdf2djvu: fix build on GCC architectures

When compiling with GCC, as used on GCC architectures, it errors with:
sys-uuid.cc:96:12: error: 'strlen' was not declared in this scope

assert(strlen(s) == 36U);
       ^~~~~~

sys-uuid.cc:96:12: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?

converters/pdf2djvu: Update to 0.9.13

Remove now obsolete patches that were merged by upstream:

* Build fixes for graphics/poppler >= 0.76.0
* Improvement of build-time logging

While I'm here:
* Add path to LICENSE_FILE
* Fix no-op occurence of DOCS_DESC

Changelog:

https://github.com/jwilk/pdf2djvu/blob/0.9.13/doc/changelog

PR:		239366
Submitted by:	Samy Mahmoudi <samy.mahmoudi@gmail.com> (maintainer)

Approved by:	ports-secteam (miwi)