math/muparser: Fix pkg-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/cmake/muparser/muparser-targets-%%CMAKE_BUILD_TYPE%%.cmake
Error: Orphaned: lib/cmake/muparser/muparser-targets.cmake
Error: Orphaned: lib/cmake/muparser/muparserConfig.cmake
Error: Orphaned: lib/cmake/muparser/muparserConfigVersion.cmake

Approved by:	portmgr (blanket)