MFH: r514655
sysutils/grub2-bhyve: fix build on 13-CURRENT

Build error: ./stdio.h:456:1: error: 'gets' undeclared here (not in a
             function); did you mean 'getw'?

grub2 doesn't use gets() at all so it's just an error in the glib header
file as a result of gets being excised from FreeBSD. Commenting out the
_GL_WARN_ON_USE macro for that is fine.

PR:		241168
Submitted by:	Robert James Hernandez <rob@sarcasticadmin.com>
Approved by:	grehan (maintainer)

Approved by:	ports-secteam (joneum)