Fix configure error when SESSION is enabled
In file included from <built-in>:318:
<command line>:39:28: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define SQLITE_ENABLE_RTREE-DSQLITE_ENABLE_SESSION 1
                           ^
sqlite3.c:308:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SQLITE_ENABLE_RTREE
    ^~~~~~~~~~~~~~~~~~~
<command line>:39:52: note: expanded from here
#define SQLITE_ENABLE_RTREE-DSQLITE_ENABLE_SESSION 1
                           ~~~~~~~~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
*** Error code 1

Approved by:	portmgr (blanket)

(cherry picked from commit 3a63ed21533b22496003b59998350d606b99a630)