net/gerbera: Update to 3.2.1 and mark BROKEN on i386
Fails to build on i386,
error: non-constant-expression cannot be narrowed from type 'rep' (aka 'long long') to 'time_t' (aka 'int') in initializer list

Changelog: https://github.com/gerbera/gerbera/releases/tag/v3.2.1