MFH: r512436
Fix groff build with libc++ 9.0.0

Because libc++ 9.0.0 now includes <math.h> from <stdlib.h>, groff fails
to build with an error similar to:

In file included from src/libs/libgroff/assert.cpp:20:
In file included from /usr/include/c++/v1/stdlib.h:100:
./lib/math.h:38:3: error: "Please include config.h first."
 #error "Please include config.h first."
  ^
./lib/math.h:40:1: error: unknown type name '_GL_INLINE_HEADER_BEGIN'
_GL_INLINE_HEADER_BEGIN
^

Fix this in the least intrusive way, by simply including config.h
instead of emitting an error message.

Approved by:	portmgr (joneum)
PR:		240701