MFH: r430521
print/hpijs: unbreak with libc++ 3.9

registry.cpp:249:9: error: cannot initialize a variable of type 'char *' with an rvalue of type
      'const char *'
                char    *cmdStr = strstr ((const char *) DevIDBuffer+2, "CMD:");
                         ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dj3320.cpp:429:24: error: assigning to 'char *' from incompatible type 'const char *'
            if ((pcStr = strstr((const char*)pLDLEncap->byStatusBuff + 10, "$S:")) == NULL)
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PR:		212343
Regressed by:	https://github.com/llvm-mirror/libcxx/commit/b4aa97130b8b