devel/libccid: build fix
Link against pthread, otherwise we fail to build:

	libtool: link: cc -I/usr/local/include/PCSC -DSIMCLIST_NO_DUMPRESTORE -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fstack-protector-strong -o parse parse-parse.o parse-debug.o parse-ccid_usb.o parse-sys_unix.o parse-tokenparser.o parse-strlcpy.o parse-simclist.o  -lusb -L/lib -lz
	/usr/local/bin/x86_64-unknown-freebsd15.0-ld: parse-ccid_usb.o: undefined reference to symbol 'pthread_create@@FBSD_1.0'
	/usr/local/bin/x86_64-unknown-freebsd15.0-ld: /lib/libthr.so.3: error adding symbols: DSO missing from command line
	cc: error: linker command failed with exit code 1 (use -v to see invocation)