MFH: r410000
security/nss: unbreak build on 9.x after r409978

Drop -ansi as it often breaks build e.g., C++-style comments in C code.

secasn1d.c: In function 'sec_asn1d_parse_leaf':
secasn1d.c:1611: error: expected expression before '/' token
secasn1d.c:1622: error: expected expression before '/' token
secasn1d.c:1629: error: expected expression before '/' token
secasn1d.c:1621: warning: unused variable 'len_in_bits'

Reported by:	pkg-fallout
Pointy hat:	jbeich
Approved by:	ports-secteam bustage fix blanket