deskutils/foliate: Fix check-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/glib-2.0/schemas/com.github.johnfactotum.Foliate.gschema.xml

GLIB_SCHEMAS are auto-added to the plist.  No need to list them
twice.