MFH: r508722 r508754
www/chromium: Update to 76.0.3809.100

Changelog: https://chromium.googlesource.com/chromium/src/+log/75.0.3770.142..76.0.3809.100?pretty=fuller&n=10000

Submitted by:	Matthias Wolf <matthias@rheinwolf.de>

www/chromium: Sync sndio backend with OpenBSD and unbreak build after r508722

../../media/audio/openbsd/audio_manager_openbsd.cc:158:14: error: allocating an object of abstract class type 'media::SndioAudioOutputStream'
  return new SndioAudioOutputStream(params, this);
             ^
../../media/audio/audio_io.h:117:16: note: unimplemented pure virtual method 'Flush' in 'SndioAudioOutputStream'
  virtual void Flush() = 0;

PR:		239802
Submitted by:	tobik
Reported by:	kib
Tested by:	kib
Approved by:	chromium (cpm)

Approved by:	ports-secteam (miwi)