MFH: r552103
security/heaan: fix build on GCC architectures

Patch created manually, because WRKSRC differs.
Add include sys/time.h:
In file included from ../src/TestScheme.cpp:20:
../src/TimeUtils.h:20:17: error: field 'startTime' has incomplete type 'timeval'
   20 |  struct timeval startTime, stopTime;
      |                 ^~~~~~~~~

Approved by:	portmgr (fix build blanket)