net/fragroute: Unbreak on CURRENT
fragtest.c:102:39: warning: implicit declaration of function 'TAILQ_END' is invalid in C99 [-Wimplicit-function-declaration]
        for (pkt = TAILQ_FIRST(pktq); pkt != TAILQ_END(pktq); pkt = next) {
                                             ^

It was accidentally using sys/queue.h (which no longer has TAILQ_END)
instead of the bundled version.  Make this explicit and add a
definition for TAILQ_END to avoid adding more patches.