lang/libhx: fix build with lld 17
Building lang/libhx with lld 17 results in the following link errors:

  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_basename' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_basename_exact' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_chomp' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_copy_dir' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_copy_file' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_dirname' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_dlclose' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_dlerror' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_dlopen' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_dlsym' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_drand' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_exit' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_ffs' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_fls' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getl' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getopt' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getopt_help' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getopt_help_cb' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getopt_usage' failed: symbol not defined
  ld: error: version script assignment of 'LIBHX_3.25' to symbol 'HX_getopt_usage_cb' failed: symbol not defined

Since the linker version script is also used for a "rtcheck" library
which does not implement any of the symbols, suppress errors with lld >=
17 due to these undefined symbols.

PR:		273753
MFH:		2023Q4