devel/riscv64-none-elf-gcc: Fix PLIST
- Bump PORTREVISION for package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/crtbegin.o
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/crtend.o
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/crti.o
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/crtn.o
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/libgcc.a
Error: Orphaned: lib/gcc/%%GCC_TARGET%%/%%GCC_VERSION%%/rv64imafdc/lp64d/libgcov.a
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)