www/neon: Bump PORTREVISION for package change after b43b9dbb497b70eb322c51b6479be22170f763aa
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/locale/ka/LC_MESSAGES/neon.mo
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)