MFH: r523492
lang/spidermonkey60: fix build on i386

Build used to fail with

Unified_cpp_js_src_jsapi-tests0.o: In function `cls_testAtomicOperationsU64::run(JS::Handle<JSObject*>)':
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x86): undefined reference to `__atomic_load_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0xd0): undefined reference to `__atomic_store_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x111): undefined reference to `__atomic_exchange_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x185): undefined reference to `__atomic_compare_exchange_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x200): undefined reference to `__atomic_compare_exchange_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x268): undefined reference to `__atomic_fetch_add_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x2c5): undefined reference to `__atomic_fetch_sub_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x324): undefined reference to `__atomic_fetch_and_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x384): undefined reference to `__atomic_fetch_or_8'
...[_ZN27cls_testAtomicOperationsU643runEN2JS6HandleIP8JSObjectEE]+0x3e4): undefined reference to `__atomic_fetch_xor_8'

Switch to using gcc on i386.

Approved by:	ports-secteam (blanket)