MFH: r478228
dns/void-zones-tools: Respect CFLAGS and avoid using -march=native

It currently compiles with -march=native which breaks on some
machines

cc  -march=native -mssse3 -ffast-math -std=c11 -g0 -Ofast -fstrict-aliasing -Wno-parentheses binutils.c -c -o binutils.o
error: unknown target CPU 'k6-3'

Given that the build is currently targeting the build host CPU,
existing binary packages on pkg.FreeBSD.org (or elsewhere) might
be broken on many machines too, so bump PORTREVISION to trigger a
rebuild.

PR:		230899
Submitted by:	tobik
Reported by:	Marco Beishuizen <mbeis@xs4all.nl>
Approved by:	Vidar Karlsen <vidar@karlsen.tech> (maintainer)

Approved by:	ports-secteam (miwi)