Mark "BROKEN" on mips and mips64
/nxb-bin/usr/bin/cc -c -O2 -pipe -G0 -EB -mabi=64 -msoft-float  -fno-strict-aliasing  -I /usr/local/include -I
src/core  -I src/event  -I src/event/modules  -I src/os/unix  -I objs  -o objs/src/core/ngx_spinlock.o  src/core/ngx_spinlock.c
src/core/ngx_spinlock.c:47:2: error: #error ngx_spinlock() or ngx_atomic_cmp_set() are not defined !
*** Error code 1

Reported by:	pkg-fallout
Sponsored by:	Netzkommune GmbH

(cherry picked from commit e9a9a800430ac12e87861b4f96714c5837ec2224)