Mark BROKEN: fails to build
clamav_mod.c:126:33: error: use of undeclared identifier 'CL_SCAN_STDOPT'

Reported by:	pkg-fallout

(cherry picked from commit 0c8dedd1c9f8ba5363d0129118b7a369b9126d13)