MFH: r490545
databases/pgpool-II-40: Actually unbreak PAM option after r490475

Do not pass --without-pam to configure as it does not appear to
work correctly.  It also defines USE_PAM in config.h even when it
should not be defined and the build breaks.

auth/pool_hba.c:157:24: error: variable has incomplete type 'struct pam_conv'
static struct pam_conv pam_passw_conv = {
                       ^

http://beefy3.nyi.freebsd.org/data/112amd64-quarterly/490502/logs/errors/pgpool-II40-4.0.2_2.log

Pointy hat:	tobik
Approved by:	tz (maintainer)

Approved by:	ports-secteam build fix blanket