MFH: r457814
Make smartmontools 6.6 compile with clang 6.0.0 and higher

Because clang 6.0.0 and higher default to -std=gnu++14, like gcc 6 and
higher, compiling smartmontools results in the following error:

os_freebsd.cpp:487:45: error: invalid suffix on literal; C++11 requires
a space between literal and identifier [-Wreserved-user-defined-literal]
  else if (sscanf(dev, NVME_CTRLR_PREFIX"%d"NVME_NS_PREFIX"%d%c",
                                            ^

Fix this by adding spaces around the NVME_NS_PREFIX macro. This makes
the source C++14 compatible.

Approved by:	portmgr (zi)
Approved by:	samm@os2.kiev.ua (maintainer)
PR:		224826