MFH: r418330
Declare missing dependencies to pass `make stage-qa'.

Error: /usr/local/bin/qbs is linked to /usr/local/lib/libQt5Core.so.5 from devel/qt5-core but it is not declared as a dependency
Warning: you need USE_QT5+=core
Error: /usr/local/bin/qbs-config-ui is linked to /usr/local/lib/.mesa/libGL.so from graphics/libGL but it is not declared as a dependency
Warning: you need USE_GL+=gl
Error: /usr/local/lib/libqbscore.so.1.5.2 is linked to /usr/local/lib/libQt5Network.so.5 from net/qt5-network but it is not declared as a dependency
Warning: you need USE_QT5+=network

Approved by:	ports-secteam (junovitch)