multimedia/gst123: Fix build with ncurses 6.6
Apply the upstream patch to fix the build.
Update USE_GSTREAMER and USE_XORG.
Since it has been a while since the version was updated, remove the
pkg-message for migration.

In file included from gst123.cc:33:
./terminal.h:31:30: error: field has incomplete type 'struct termios'
   31 |   struct termios             tio_orig;
      |                              ^
./terminal.h:31:10: note: forward declaration of 'termios'
   31 |   struct termios             tio_orig;
      |          ^

PR:		292500
Approved by:	fluffy (mentor)