MFH: r484695
emulators/qemu: fix build on 12 and -CURRENT

Build fails with:

hw/rdma/vmw/pvrdma_cmd.c:19:10: fatal error: 'linux/types.h' file not found

Add two upstream commits to fix this issue:

 * 72221d03b85fcfba27a47a2af08ee59150550ced to not include linux/types.h
 * 21ab34c9543fe1b6d31b3edbd01a397e7e090d00 to split PVRDMA from RDMA as
   pvrdma device can't be used on FreeBSD as mremap() system call is
   missing

PR:		232968
Reported by:	Trond.Endrestol@ximalas.info
Approved by:	portmgr (build fix blanket)
Obtained from:	upstream

Approved by:	ports-secteam (miwi)