MFH: r448460
net/czmq: Squash -Werror flag

zmq_utils.h functionality was moved to zmq.h since 4.2.0, with a deprecation
warning added. ports r448376 updated libzm4 to 4.2.2, which caused a build error
in net/cmzq due to the -Werror flag (set by default):

  /usr/local/include/zmq_utils.h:41:32: error: unknown warning group '-Werror', ignored [-Werror,-Wunknown-warning-option]
  #pragma GCC diagnostic ignored "-Werror"
                                 ^
  /usr/local/include/zmq_utils.h:44:9: warning: Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h. [-W#pragma-messages]
  #pragma message("Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.")
          ^

Squash the -Werror flag (as done in net/libzmq4) accordingly.

While I'm here:

- Modernize test target
- Group build related entries (MAKE_ENV/CPPFLAGS)

PR:		221688
Reported by:	olgeni, Jan Bramkamp <crest_maintainer rlwinm de>

Approved by:	ports-secteam (blanket)