MFH: r431742
www/webkit-qt4: unbreak with clang 4.0

html/HTMLImageElement.cpp:77:24: error: ordered comparison between pointer and zero ('const int *' and 'int')
    if (optionalHeight > 0)
        ~~~~~~~~~~~~~~ ^ ~

PR:		216015
Regressed by:	https://github.com/llvm-mirror/clang/commit/4b6ad14285f3
Obtained from:	upstream (excerpt)
Approved by:	portmgr blanket
Approved by:	ports-secteam blanket