MFH: r568164
multimedia/arcan: unbreak on aarch64

(encode) disabled, lzma not found
[...]
Determining if the function lzma_auto_decoder exists in the /usr/lib/liblzma.so failed with the following output:
c++: error: the clang compiler does not support '-march=native'
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: bin/afsrv_encode

PR:		254234
Reported by:	mikael