graphics/egl-wayland: unbreak afte r558099
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libnvidia-egl-wayland.so.1.1.6
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/libnvidia-egl-wayland.so.1.1.5
===> Error: Plist issues found.
*** Error code 1

PR:		251843
Submitted by:	VVD