MFH: r530763
net/tigervnc-server: fix build on GCC architectures

C11 compiler is required:
../include/glx_extinit.h:33: error: redefinition of typedef '__GLXscreen'

Approved by:	portmgr (fix build blanket)