Fix build.
cc -std=c11 -pedantic -DREDIS_STATIC='' -Wall -W -Wno-missing-field-initializers   -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -MMD -o lzf_c.o -c lzf_c.c
zmalloc.c:59:5: error: function-like macro 'sizeof' is not defined
#if PREFIX_SIZE > 0
    ^
zmalloc.c:55:22: note: expanded from macro 'PREFIX_SIZE'
#define PREFIX_SIZE (sizeof(size_t))
                     ^
1 error generated.
gmake[3]: *** [Makefile:339: zmalloc.o] Error 1

Do not bump PORTREVISION because these have no successful
builds.

Reported by:	many