MFH: r533909
In file included from /usr/obj/usr/ports/databases/mysql57-client/work/mysql-5.7.30/vio/viosslfactories.c:29:
/usr/obj/usr/ports/databases/mysql57-client/work/mysql-5.7.30/include/my_openssl.h:55:30: error: use of undeclared identifier 'OPENSSL_INIT_NO_ATEXIT'
  return OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);

This fix a problem with libressl

PR:		246070
Sponsored by:	Netzkommune GmbH

Approved by:	ports-secteam (joneum)

(cherry picked from commit 717c23e2adb53ba8aef30f8226b771e5a8cb7e4e)