As of the 5.0.0 commit, this port now includes python code that is only available in Python 3:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 41
    print(error, file=sys.stderr)
                     ^
  SyntaxError: invalid syntax

Accordingly, restrict the port and remove the special-case code.

Approved by:	portmgr ("just fix it")