lang/rust: unbreak if ssl != base
  [ 13%] Building C object src/CMakeFiles/libssh2.dir/channel.c.o
  /usr/bin/cc -DLIBSSH2_CLEAR_MEMORY -DLIBSSH2_DH_GEX_NEW=1 -DLIBSSH2_HAVE_ZLIB=1 -DLIBSSH2_OPENSSL -I/usr/local/include -Isrc/vendor/libssh2-sys/libssh2/include -Ibuild/x86_64-unknown-freebsd/stage2-tools/x86_64-unknown-freebsd/release/build/libssh2-sys-149db94635ec1367/out/build/src  -ffunction-sections -fdata-sections -fPIC -ffunction-sections -fdata-sections -fPIC -m64 -m64 -O3 -DNDEBUG   -std=gnu90 -o CMakeFiles/libssh2.dir/channel.c.o   -c src/vendor/libssh2-sys/libssh2/src/channel.c
  src/vendor/libssh2-sys/libssh2/src/channel.c:2262:44: error: use of undeclared identifier 'LIBSSH2_ERROR_CHANNEL_WINDOW_FULL'
	      return _libssh2_error(session, LIBSSH2_ERROR_CHANNEL_WINDOW_FULL,
					     ^

PR:		231411
Reported by:	many
Obtained from:	upstream (libssh2)
Approved by:	portmgr blanket

(cherry picked from commit fdc68411814d909375f3d0a34db512983fcc4d23)