graphics/waifu2x-ncnn-vulkan: update to 20200414
Previous version stopped building after r531698:

src/waifu2x.cpp:123:34: error: no matching member function for call to 'create'
                waifu2x_preproc->create(waifu2x_preproc_tta_int8s_spv_data, sizeof(waifu2x_preproc_tta_int8s_spv_data), "waifu2x_preproc_tta_int8s", specializations, 9, 9);
                ~~~~~~~~~~~~~~~~~^~~~~~
/usr/local/include/ncnn/pipeline.h:44:9: note: candidate function not viable: requires 4 arguments, but 6 were provided
    int create(VkShaderModule shader_module, const std::vector<vk_specialization_type>& specializations, int binding_count, int push_constant_count);
        ^
/usr/local/include/ncnn/pipeline.h:40:9: note: candidate function not viable: requires 3 arguments, but 6 were provided
    int create(const uint32_t* spv_data, size_t spv_data_size, const std::vector<vk_specialization_type>& specializations);
        ^
/usr/local/include/ncnn/pipeline.h:42:9: note: candidate function not viable: requires 3 arguments, but 6 were provided
    int create(int shader_type_index, const Option& opt, const std::vector<vk_specialization_type>& specializations);
        ^

Changes:	https://github.com/nihui/waifu2x-ncnn-vulkan/compare/20200224...20200414
Reported by:	GitHub (watch releases)