graphics/libheif: unbreak after 17339df99b0c
libheif/plugins/encoder_svt.cc:850:37: error: assigning to 'PredStructure' from \
incompatible type 'int'
  850 | 	svt_config.pred_structure = 2; // RANDOM_ACCESS
      |                                     ^

Reported by:	Tatsuki Makino, mfechner
Regressed by:	https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/3b5e5e8d4dda
Obtained from:	upstream (open PR)