Regenerate and fix a bug resulting in: -O0-pipe
error: invalid integral value '0-pipe' in '-O0-pipe'
(cherry picked from commit 653a6d6fa4c0882fbeeba442d7c8fbb64991239d)