MFH: r463856
print/harfbuzz-icu: pacify check-plist after r464304

===========================================================================
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: bin/hb-subset
Error: Orphaned: include/harfbuzz/hb-subset-glyf.hh
Error: Orphaned: include/harfbuzz/hb-subset-plan.hh
Error: Orphaned: include/harfbuzz/hb-subset-private.hh
Error: Orphaned: include/harfbuzz/hb-subset.h
Error: Orphaned: lib/cmake/harfbuzz/harfbuzz-config.cmake
Error: Orphaned: lib/libharfbuzz-subset.so
Error: Orphaned: lib/libharfbuzz-subset.so.0
Error: Orphaned: lib/libharfbuzz-subset.so.%%LIBVER%%
Error: Orphaned: libdata/pkgconfig/harfbuzz-subset.pc

Pointy hat to:	jbeich
Approved by:	ports-secteam blanket