MFH: r495739
emulators/ppsspp: don't try to build on big-endian

In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.cpp: In member function 'virtual int PSPMsgDialog::Init(unsigned int)':
Core/Dialog/PSPMsgDialog.h:37:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED          0x000001B3 // OR of all options coded to display warning
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:62:49: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED'
  int optionsNotCoded = messageDialog.options & ~SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:71:59: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
  if(messageDialog.type == 0 && !(messageDialog.errorNum & 0x80000000))
                                                           ^~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:31:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO         0x00000100
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:89:31: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO'
   if((messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO) &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:28:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_YESNO              0x00000010
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:90:31: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_YESNO'
     !(messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_YESNO))
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:37:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED          0x000001B3 // OR of all options coded to display warning
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:95:32: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED'
   if (messageDialog.options & ~SCE_UTILITY_MSGDIALOG_OPTION_SUPPORTED)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:28:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_YESNO              0x00000010
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:109:31: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_YESNO'
   if((messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_YESNO) &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:31:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO         0x00000100
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:113:30: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO'
   if(messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:29:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_OK                 0x00000020
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:118:31: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_OK'
   if((messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_OK) && (size == SCE_UTILITY_MSGDIALOG_SIZE_V3))
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:30:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_NOCANCEL           0x00000080
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:125:33: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_NOCANCEL'
   if(!((messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_NOCANCEL)  && (size == SCE_UTILITY_MSGDIALOG_SIZE_V3)))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:18:
Core/Dialog/PSPMsgDialog.h:27:57: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 #define SCE_UTILITY_MSGDIALOG_OPTION_NOSOUND            0x00000002
                                                         ^~~~~~~~~~
Core/Dialog/PSPMsgDialog.cpp:127:30: note: in expansion of macro 'SCE_UTILITY_MSGDIALOG_OPTION_NOSOUND'
   if(messageDialog.options & SCE_UTILITY_MSGDIALOG_OPTION_NOSOUND)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.h:22,
                 from Core/Dialog/PSPMsgDialog.cpp:18:
Common/Swap.h:473:3: note: candidate 1: 'S operator&(const swap_struct_t<T, F>&, const S&) [with S = int; T = unsigned int; F = swap_32_t<unsigned int>]'
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
Common/Swap.h:308:12: note: candidate 2: 'swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]'
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from Core/Dialog/PSPMsgDialog.cpp:23:
Common/ChunkFile.h: In instantiation of 'void PointerWrap::DoClass(T&) [with T = pspMessageDialog]':
Common/ChunkFile.h:96:4:   required from 'static void PointerWrap::DoHelper<T, isPOD, isPointer>::Do(PointerWrap*, T&) [with T = pspMessageDialog; bool isPOD = false; bool isPointer = false]'
Common/ChunkFile.h:496:18:   required from 'void PointerWrap::Do(T&) [with T = pspMessageDialog]'
Core/Dialog/PSPMsgDialog.cpp:321:20:   required from here
Common/ChunkFile.h:475:5: error: 'struct pspMessageDialog' has no member named 'DoState'
   x.DoState(*this);
   ~~^~~~~~~

Reported by:	pkg-fallout
Approved by:	ports-secteam blanket