MFH: r552973
emulators/qemu50: fix build on GCC architectures

Adding -L/usr/lib make gcc from ports prefer /usr/lib instead of its own /usr/local/lib/gcc9, which makes build fail:
/usr/local/bin/ld: accel/tcg/tcg-runtime.o: in function `clrsb32':
/wrkdirs/usr/ports/emulators/qemu50/work/qemu-5.0.0/include/qemu/host-utils.h:211: undefined reference to `__clrsbdi2'

Tested for no breakage on 12.1/i386, 12.2/amd64 and 13.0/powerpc64.

Approved by:	portmgr (fix build blanket)