www/webkit2-gtk3: fix build on powerpc64
ar is now required for build.

Include ExecutableBaseInlines.h in NativeExecutable.cpp to fix:
Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/__/__/DerivedSources/JavaScriptCore/unified-sources/UnifiedSource-f2e18ffc-27.cpp.o(.text+0x5300): error: undefined reference to 'JSC::ExecutableBase::hasJITCodeForCall() const'