audio/opustags: fix build on GCC architectures
GCC doesn't include sys/endian.h by default:
/wrkdirs/usr/ports/audio/opustags/work/opustags-1.3.0/src/opus.cc: In function 'ot::status ot::parse_tags(const ogg_packet&, ot::opus_tags&)':
/wrkdirs/usr/ports/audio/opustags/work/opustags-1.3.0/src/opus.cc:58:25: error: 'le32toh' was not declared in this scope
   58 |  size_t vendor_length = le32toh(*((uint32_t*) (data + pos)));
      |                         ^~~~~~~
/wrkdirs/usr/ports/audio/opustags/work/opustags-1.3.0/src/opus.cc: In function 'ot::dynamic_ogg_packet ot::render_tags(const ot::opus_tags&)':
/wrkdirs/usr/ports/audio/opustags/work/opustags-1.3.0/src/opus.cc:107:6: error: 'htole32' was not declared in this scope
  107 |  n = htole32(tags.vendor.size());
      |      ^~~~~~~